env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
ignorePatterns: ["coverage", "node_modules", "client/node_modules"]
rules: {
  indent: ["error", 4],
  no-undef: "off"
}
