version: '3.7'

services:
  node:
    build: ./docker/node
    tty: true
    volumes:
      - .:/app

  ganache:
    build: ./docker/ganache
    ports:
      - 8545:8545

  react:
    build: ./docker/node
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./client:/app